### ISSUE TITLE
Document how to port away from pkitool

### ISSUE THREAD

**Issue by JulienPalard** [OpenVPN/easy-rsa#414]
Hi!

I just spotted that pkitool was removed in 346adba3f36648156dcd4ed839ec2de508186f09, 7 years ago (yes I just upgraded a Raspbian to Buster).

There's my ansible playbook, and [a few scripts](https://github.com/search?l=Shell&q=pkitool&type=Code) that rely on `pkitool`, I think it would be nice to document how to "port away from" pkitool cleanly, maybe on the https://easy-rsa.readthedocs.io/en/latest/upgrade-notes/ page. Maybe easy-rsa is simply not the right tool and I should use openssl directly, I don't know, but anyway it would be nice to state it cleanly in the upgrade guide, as I think people relying on `pkitool` from easy-rsa 2 would land here after upgrading to debian/raspbian Buster (released last year, so don't except a "huge wave of angry users" tomorrow ☺).

My usage, if of any help, was to run:

    pkitool --initca &&
    pkitool --server server &&
    openssl dhparam -out $key_dir/dh2048.pem 2048

once, and then run:

    pkitool $username

when I want to add a user. It was probably not state of the art.

While I'm here, thanks for all the work on easy-rsa!

**Comment by JulienPalard** [comment]
Was able to restore a working state of my ansible playbook by using this small shell script, highly inspired from easy-rsa v2.

Disclamer: Hi stranger landing on this page by searching where's the lost pkitool! I'm in no way an openssl expert, don't trust me, don't use this in production if you don't fully understand what's your doing and why you're doing it. Following the [quickstart](https://github.com/OpenVPN/easy-rsa/blob/master/README.quickstart.md) and doing it by following the recommended procedure (with two separate systems) is probably a better way, please read it first.

Anyway, here's what I did:

```
#!/bin/sh

KEY_CONFIG={{openvpn_etcdir}}/openssl-1.0.0.cnf

export KEY_DIR="{{ openvpn_keydir }}"
export KEY_COUNTRY="{{ openvpn_key_country }}"
export KEY_PROVINCE="{{ openvpn_key_province }}"
export KEY_CITY="{{ openvpn_key_city }}"
export KEY_ORG="{{ openvpn_key_org }}"
export KEY_EMAIL="{{ openvpn_key_email }}"
export KEY_NAME="{{ openvpn_key_name }}"
export KEY_OU="{{ openvpn_key_ou }}"

export CA_EXPIRE=3650
export KEY_EXPIRE=3650
export KEY_SIZE=2048

cd "$KEY_DIR"

if [ $# = 0 ] ; then # No argument: initca
    openssl req -batch -days 3650 -nodes -new -newkey rsa:$KEY_SIZE \
        -x509 -keyout "ca.key" -out "ca.crt" -config "$KEY_CONFIG" && \
        chmod 0600 "ca.key"
else # Argument given: Create user certificate
    KEY_CN="$1"
    export KEY_CN
    openssl req -batch -nodes -new -newkey rsa:$KEY_SIZE \
            -keyout "$KEY_CN.key" -out "$KEY_CN.csr" -extensions server -config "$KEY_CONFIG"
    openssl ca -batch -days 3650 -out "$KEY_CN.crt" \
            -in "$KEY_CN.csr" -extensions server -config "$KEY_CONFIG"
    chmod 0600 "$KEY_CN.key"
fi
```

and my playbook use it as is:
```yaml
- name: Copy pkitool.sh
  template:
    src: pkitool.sh
    dest: "{{openvpn_etcdir}}/pkitool.sh"
    mode: 0700

- name: Generate Server keys
  command: "{{openvpn_etcdir}}/pkitool.sh"
  args:
    creates: "{{ openvpn_keydir }}/ca.key"

- name: Generate Clients keys
  command: "{{openvpn_etcdir}}/pkitool.sh {{item}}"
  args:
    creates: "{{ openvpn_keydir }}/{{item}}.crt"
  loop: "{{ openvpn_clients }}"
```

Note it uses an openssl.cnf from easy-rsa v2 like https://raw.githubusercontent.com/OpenVPN/easy-rsa/fd11cf19831675d92efcf7e24d709fc6be4d9e2c/easy-rsa/2.0/openssl-1.0.0.cnf

I bet this is [the wrong way to do it](https://i1.kym-cdn.com/photos/images/facebook/000/234/142/196.jpg
), and would appreciate to be enlighted to the right way.
